name: Build and Release Installers

on:
  release:
    types: [created]

jobs:
  build-and-package-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Verify Chocolatey
        run: choco --version

      - name: Install WiX Toolset
        run: choco install wixtoolset --version=3.14.1 -y

      - name: Add WiX to PATH
        run: echo "C:\\Program Files (x86)\\WiX Toolset v3.11\\bin" >> $GITHUB_PATH

      - name: Build project
        run: ./gradlew clean build

      - name: Package Windows Installer
        run: ./gradlew jpackage

      - name: Upload installers to release
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: build/installers/