name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: get permission to execute the gradlew file
      run: chmod +x ./gradlew
    - name: Build with Gradle Wrapper
      run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: get permission to execute the gradlew file
      run: chmod +x ./gradlew

    - name: Test with Gradle Wrapper
      run: |
        cd candycrush
        ./gradlew test
    
